/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-09-16 16:01:30 UTC)
 * on 2013-10-15 at 04:12:07 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.freebase.model;

/**
 * Model definition for ReconcileCandidate.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Freebase Search. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ReconcileCandidate extends com.google.api.client.json.GenericJson {

  /**
   * Percentage likelihood that this candidate is the unique matching entity. Value will be between
   * 0.0 and 1.0
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float confidence;

  /**
   * Language code that candidate and notable names are displayed in.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lang;

  /**
   * Freebase MID of candidate entity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String mid;

  /**
   * Freebase name of matching entity in specified language.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Type or profession the candidate is notable for.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Notable notable;

  /**
   * Percentage likelihood that this candidate is the unique matching entity. Value will be between
   * 0.0 and 1.0
   * @return value or {@code null} for none
   */
  public java.lang.Float getConfidence() {
    return confidence;
  }

  /**
   * Percentage likelihood that this candidate is the unique matching entity. Value will be between
   * 0.0 and 1.0
   * @param confidence confidence or {@code null} for none
   */
  public ReconcileCandidate setConfidence(java.lang.Float confidence) {
    this.confidence = confidence;
    return this;
  }

  /**
   * Language code that candidate and notable names are displayed in.
   * @return value or {@code null} for none
   */
  public java.lang.String getLang() {
    return lang;
  }

  /**
   * Language code that candidate and notable names are displayed in.
   * @param lang lang or {@code null} for none
   */
  public ReconcileCandidate setLang(java.lang.String lang) {
    this.lang = lang;
    return this;
  }

  /**
   * Freebase MID of candidate entity.
   * @return value or {@code null} for none
   */
  public java.lang.String getMid() {
    return mid;
  }

  /**
   * Freebase MID of candidate entity.
   * @param mid mid or {@code null} for none
   */
  public ReconcileCandidate setMid(java.lang.String mid) {
    this.mid = mid;
    return this;
  }

  /**
   * Freebase name of matching entity in specified language.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Freebase name of matching entity in specified language.
   * @param name name or {@code null} for none
   */
  public ReconcileCandidate setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Type or profession the candidate is notable for.
   * @return value or {@code null} for none
   */
  public Notable getNotable() {
    return notable;
  }

  /**
   * Type or profession the candidate is notable for.
   * @param notable notable or {@code null} for none
   */
  public ReconcileCandidate setNotable(Notable notable) {
    this.notable = notable;
    return this;
  }

  @Override
  public ReconcileCandidate set(String fieldName, Object value) {
    return (ReconcileCandidate) super.set(fieldName, value);
  }

  @Override
  public ReconcileCandidate clone() {
    return (ReconcileCandidate) super.clone();
  }

  /**
   * Type or profession the candidate is notable for.
   */
  public static final class Notable extends com.google.api.client.json.GenericJson {

    /**
     * MID of notable category.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String id;

    /**
     * Name of notable category in specified language.
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private java.lang.String name;

    /**
     * MID of notable category.
     * @return value or {@code null} for none
     */
    public java.lang.String getId() {
      return id;
    }

    /**
     * MID of notable category.
     * @param id id or {@code null} for none
     */
    public Notable setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    /**
     * Name of notable category in specified language.
     * @return value or {@code null} for none
     */
    public java.lang.String getName() {
      return name;
    }

    /**
     * Name of notable category in specified language.
     * @param name name or {@code null} for none
     */
    public Notable setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @Override
    public Notable set(String fieldName, Object value) {
      return (Notable) super.set(fieldName, value);
    }

    @Override
    public Notable clone() {
      return (Notable) super.clone();
    }

  }
}
